# ################################## #
#       Kitty customization file     #
# ################################## #

shell_integration enabled
map ctrl+shift+t new_tab_with_cwd

enable_audio_bell no

font_size 12
modify_font cell_height 95%

# kitten choose-fonts
font_family      JetBrains Mono

remember_window_size  no
# initial_window_width  640
# initial_window_height 400
initial_window_width  840
initial_window_height 600

# ################################## #
#       Tabbar customization         #
# ################################## #
tab_bar_edge top

tab_bar_style powerline
tab_powerline_style slanted

active_tab_background   #3c3836
active_tab_foreground   #ebdbb2

inactive_tab_background #282828
inactive_tab_foreground #928374

tab_bar_background #1d2021

tab_separator " "
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0

tab_font_style normal
tab_bar_min_tabs 2

# option for long titles
# tab_title_template "{index}"

# ################################## #
# Theme from Ghostty "Retro Legend"  #
# ################################## #
background #0d0d0d
foreground #45eb45
selection_foreground #0d0d0d
selection_background #336633

color0 #262626
color1 #de5454
color2 #45eb45
color3 #f7bf2b
color4 #4066f2
color5 #bf4cf2
color6 #40d9e6
color7 #bfe6bf
color8 #4c594c
color9 #ff6666
color10 #59ff59
color11 #ffd933
color12 #4c80ff
color13 #e666ff
color14 #59e6ff
color15 #f2fff2

